language: node_js
node_js:
  - "node"
dist: trusty
cache: npm
before_install:
  - npm --version
branches:
  only:
    - master
env:
  - TEST_SUITE=test
  - TEST_SUITE=test-security
script:
  - npm run $TEST_SUITE
